feat: Core migration to node v2 with testing framework, wallet. Still needs revamp on cli tools

diff --git a/cartesapp/Makefile b/cartesapp/Makefile
--- a/cartesapp/Makefile
+++ b/cartesapp/Makefile
@@ -8,7 +8,7 @@ define setup_venv =
 @if [ ! -d .venv ]; then python3 -m venv .venv; fi
 @if [[ "VIRTUAL_ENV" != "" ]]; then . .venv/bin/activate; fi
 @if [ -z "$(pip freeze)" ]; then
-	if [ -f requirements.txt ]; then 
+	if [ -f requirements.txt ]; then
 		pip install -r requirements.txt;
 	else
 		pip install git+https://github.com/prototyp3-dev/cartesapp@main --find-links https://prototyp3-dev.github.io/pip-wheels-riscv/wheels/
@@ -38,8 +38,8 @@ build-dev-node: ; $(value setup_venv)
 build-%: ${ENVFILE}.% --check-envs-% ; $(value setup_venv)
 	. $< && cartesapp build $(ARGS)
 	# You can add build args or env from the envfile
-	#   add docker build-args with: --config build-args=ENV1=${ENV1},ENV2=${ENV2} 
-	#   add docker cm envs with: --config envs=ENV3=${ENV3},ENV4=${ENV4} 
+	#   add docker build-args with: --config build-args=ENV1=${ENV1},ENV2=${ENV2}
+	#   add docker cm envs with: --config envs=ENV3=${ENV3},ENV4=${ENV4}
 
 # Run targets
 run: --load-env --check-roladdr-env ; $(value setup_venv)
@@ -53,10 +53,10 @@ run-reader: ; $(value setup_venv)
 
 run-dev-%: ${ENVFILE}.% --check-testnet-envs-% --check-dev-envs-% rivemu ; $(value setup_venv)
 	. $< && ROLLUP_HTTP_SERVER_URL=${ROLLUP_HTTP_SERVER_URL} \
-	 cartesapp node --mode dev --rpc-url=${RPC_URL} --contracts-application-address=${DAPP_ADDRESS} --contracts-input-box-block=${DAPP_DEPLOY_BLOCK} $(ARGS)
+	 cartesapp node --mode dev --rpc-url=${RPC_URL} --contracts-application-address=${APP_CONTRACT} --contracts-input-box-block=${DAPP_DEPLOY_BLOCK} $(ARGS)
 
 run-reader-%: ${ENVFILE}.% --check-testnet-envs-% ; $(value setup_venv)
-	. $< && cartesapp node --mode reader --rpc-url=${RPC_URL} --contracts-application-address=${DAPP_ADDRESS} --contracts-input-box-block=${DAPP_DEPLOY_BLOCK} $(ARGS)
+	. $< && cartesapp node --mode reader --rpc-url=${RPC_URL} --contracts-application-address=${APP_CONTRACT} --contracts-input-box-block=${DAPP_DEPLOY_BLOCK} $(ARGS)
 
 # Test targets
 test-verbose: ; $(value setup_venv)
@@ -68,7 +68,7 @@ test-verbose: ; $(value setup_venv)
 	$(eval include include $(PWD)/${ENVFILE})
 
 ${ENVFILE}:
-	@test ! -f $@ && echo "$(ENVFILE) not found. Creating with default values" 
+	@test ! -f $@ && echo "$(ENVFILE) not found. Creating with default values"
 	echo ROLLUP_HTTP_SERVER_URL=http://localhost:5004/rollup >> $(ENVFILE)
 
 --load-env-%: ${ENVFILE}.%
@@ -89,6 +89,5 @@ ${ENVFILE}.%:
 
 --check-testnet-envs-%: --load-env-%
 	@test ! -z '${RPC_URL}' || echo "Must define RPC_URL in env" && test ! -z '${RPC_URL}'
-	@test ! -z '${DAPP_ADDRESS}' || echo "Must define DAPP_ADDRESS in env" && test ! -z '${DAPP_ADDRESS}'
+	@test ! -z '${APP_CONTRACT}' || echo "Must define APP_CONTRACT in env" && test ! -z '${APP_CONTRACT}'
 	@test ! -z '${DAPP_DEPLOY_BLOCK}' || echo "Must define DAPP_DEPLOY_BLOCK in env" && test ! -z '${DAPP_DEPLOY_BLOCK}'
-
